import { seedEntity } from "./seedEntity";
import { ISimulation, SimulationsModel } from "../entities/simulations";

seedEntity<ISimulation>(
  [
    {
      id: 1,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 1,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 2,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 1,
      valueBetMultiplier: 1,
      odBet: 9.4,
    },
    {
      id: 3,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 15,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 4,
      betEachXRounds: 1,
      currentBalance: 200,
      initialBalance: 200,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 5,
      betEachXRounds: 1,
      currentBalance: 200,
      initialBalance: 200,
      valueBet: 20,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 6,
      betEachXRounds: 1,
      currentBalance: 200,
      initialBalance: 200,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 15.4,
    },
    {
      id: 7,
      betEachXRounds: 1,
      currentBalance: 200,
      initialBalance: 200,
      valueBet: 2,
      valueBetMultiplier: 1,
      odBet: 30.4,
    },
    {
      id: 8,
      betEachXRounds: 1,
      currentBalance: 100000,
      initialBalance: 100000,
      valueBet: 1000,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 9,
      betEachXRounds: 1,
      currentBalance: 100000,
      initialBalance: 100000,
      valueBet: 1,
      valueBetMultiplier: 1,
      odBet: 10000,
    },
    {
      id: 10,
      betEachXRounds: 1,
      currentBalance: 200,
      initialBalance: 200,
      valueBet: 10,
      valueBetMultiplier: 1,
      odBet: 4.4,
    },
    {
      id: 11,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 1,
      valueBetMultiplier: 1,
      odBet: 9.4,
    },
    {
      id: 12,
      betEachXRounds: 1,
      currentBalance: 600,
      initialBalance: 600,
      valueBet: 1,
      valueBetMultiplier: 1,
      odBet: 800,
    },
    {
      id: 13,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.5,
    },
    {
      id: 14,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.8,
    },
    {
      id: 15,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 2,
      odBet: 1.5,
    },
    {
      id: 16,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 3,
      odBet: 1.5,
    },
    {
      id: 17,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 4,
      odBet: 1.5,
    },

    {
      id: 18,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 5,
      odBet: 1.5,
    },
    {
      id: 19,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.4,
    },
    {
      id: 20,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.3,
    },
    {
      id: 21,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.2,
    },
    {
      id: 22,
      betEachXRounds: 1,
      currentBalance: 60,
      initialBalance: 60,
      valueBet: 4,
      valueBetMultiplier: 1,
      odBet: 1.1,
    },
  ],
  SimulationsModel
);
